INSERT INTO FOOD (ID, NAME) VALUES (1, 'Spagety');
INSERT INTO COOKING(COOK_DATE, PRICE, FOOD_ID) VALUES('2016-09-27', 55.4, 1);
INSERT INTO EXPENSE(ID, DATE, AMOUNT, EXPENSE_TYPE, NOTE) VALUES(1, '2016-09-27',  4, 'FOOD', 'it was tasty!');
INSERT INTO EXPENSE(ID, DATE, AMOUNT, EXPENSE_TYPE, NOTE) VALUES(2, '2017-09-27', 51, 'FUN', 'Enemy KIA');