/*
DROP TABLE ENUM_VALUES IF EXISTS;
DROP TABLE ENUMERATION IF EXISTS; 

CREATE TABLE ENUMERATION (
	EID INTEGER,
	NAME VARCHAR(24) NOT NULL,
	PRIMARY KEY (EID)
);

CREATE TABLE ENUM_VALUES (
	EVID INTEGER,
	EID INTEGER,
	ECODE VARCHAR(16) NOT NULL,
	ORDERING INTEGER,
	PRIMARY KEY (EVID),
	FOREIGN KEY (EID) REFERENCES ENUMERATION(EID)
);
*/